"
I represent the mapping between the instanceVariable names and the indexes of them.
"
Class {
	#name : #EPInstanceVariableMapping,
	#superclass : #Object,
	#category : 'Espell-LowLevel-Mirrors'
}

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classFormatIndex [
	^ 3
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classInstanceVariableNamesIndex [
	^ 5
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classMethodDictionaryIndex [
	^ 2
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classNameIndex [
	^ 8
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classNumberOfVariables [
	^ 14
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classPoolIndex [
	^ 9
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classSharedPoolsIndex [
	^ 10
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> classSuperclassIndex [
	^ 1
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextClosureOrNilIndex [
	^ 5
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextMethodIndex [
	^ 4
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextPcIndex [
	^ 2
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextReceiverIndex [
	^ 6
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextSenderIndex [
	^ 1
]

{ #category : #'context-instance-variables' }
EPInstanceVariableMapping >> contextStackpIndex [
	^ 3
]

{ #category : #'dictionary-instance-variables' }
EPInstanceVariableMapping >> dictionaryArrayIndex [
	^ 2
]

{ #category : #'class-instance-variables' }
EPInstanceVariableMapping >> listOfClassSlots [
	^ 'superclass methodDict format layout instanceVariables organization subclasses name classPool sharedPools environment category traitComposition localSelectors'
]

{ #category : #'process-instance-variables' }
EPInstanceVariableMapping >> processContextIndex [
	^ 2
]

{ #category : #'process-instance-variables' }
EPInstanceVariableMapping >> processNameIndex [
	^ 5
]

{ #category : #'process-instance-variables' }
EPInstanceVariableMapping >> processNextLinkIndex [
	^ 1
]

{ #category : #'process-instance-variables' }
EPInstanceVariableMapping >> processPriorityIndex [
	^ 3
]

{ #category : #'process-instance-variables' }
EPInstanceVariableMapping >> processPriorityListIndex [
	^ 4
]

{ #category : #'process-scheduler-instance-variables' }
EPInstanceVariableMapping >> processSchedulerActiveProcessIndex [
	^ 2
]

{ #category : #'smalltalkImage-instance-variables' }
EPInstanceVariableMapping >> smalltalkImageGlobalsIndex [
	^ 1
]

{ #category : #'trait-instance-variables' }
EPInstanceVariableMapping >> traitClassTraitIndex [
	^ 8
]

{ #category : #'trait-instance-variables' }
EPInstanceVariableMapping >> traitMethodDictionaryIndex [
	^ 1
]

{ #category : #'trait-instance-variables' }
EPInstanceVariableMapping >> traitNameIndex [
	^ 6
]
